### PR TITLE
Update german

### PR DESCRIPTION
**Pull request by Andre601**
While I'm at it would I like to propose to setup some translation page like a Crowdin Project (They support Open Source with a free plan) as translating this starts to become a tedious task now, since I always have to compare what is new and what isn't and what just changed slightly.

In addition would it be more beneficial for everyone to have more readable placeholders. So instead of `%s` have something like `{prefix}` so that people translating the file are aware that this may be the prefix of the plugin.
Otherwise are we just seing a lot of `%s` and `%d` without any clear indicator what exactly it would display in the end. Downside would be more work on your end as you would need to implement a logic to replace those placeholders with their right values.

### CODE REVIEW

**Comment by pop4959** [comment]
Thanks for the update, Andre! Also I agree, as I am fully aware of the downsides of the current system for translation, and this is something that I would like to improve. Crowdin sounds like a good start.

I was also already thinking about placeholders, and my thoughts were that using a style similar to how Essentials handles them might be best (for example `{0}`, `{1}`, etc, for each value being translated). The reason is because it moves a step away from the format specifiers (`%s`, `%.2f`, etc) which can be confusing. The upside of this is that it should be very easy to implement and maintain code-wise. Named placeholders on the other hand would need to be defined per-translation in code, which is more work on my side, but provides even more context to translators. Ideally there is something that works easily on both sides, but I don't know off the top of my head. Let me know if you have any opinions or other ideas of how this could be handled.

**Review by pop4959 — APPROVED** [review]

**Comment by Andre601** [comment]
An idea could be to just have a major method for translating the most generic/most used placeholders, which are also guaranteed to return the same output (such as `{prefix}`) and for more unique ones to either replace them on the spot (Where it's called) or through a more elaborate system in place where you could f.e. provide a String, object pair, that would handle the more unique cases, but that would be a really tough system to have.

It could be really hard to find the perfect middle ground here.

**Comment by pop4959** [comment]
Yeah now you see why I haven't done it yet. Although it's best done sooner than later, else I have even more work to re-do it all again in the event that it isn't sufficient. 😄 

Also, I just put in a request for an open source Crowdin license. We'll see how that goes.

**Comment by pop4959** [comment]
Looks good so far. I just set the integration up if you want to take a look at it here: https://crowdin.com/project/chunky

**Pull request merged**
