### PR TITLE
Add a "status" command

### PR DESCRIPTION
**Pull request by Jamalam360**
I've been using your mod to generate chunks in my server, but I found I wanted a status command that just returns the update message of the GenerationTask. 

I've tested it on Fabric and it works fine, and I've attempted to implement it on the other platforms based on your code, but I've never worked with commands on those platforms so I'm unsure if it is done correctly.

Thanks for making such an easy to use mod 👍

### CODE REVIEW

**Comment by RDKRACZ** [comment]
Uhhh https://github.com/pop4959/Chunky/commit/e80df2186a92d63b71af1fb915757c497c518559
https://github.com/pop4959/Chunky/issues/84#issuecomment-882005728

**Comment by pop4959** [comment]
I'm pretty sure I implemented this just last night. Have you tried the progress command? You can grab the latest build from actions and try it.

**Comment by pop4959** [comment]
Yeah so now that I'm not on my phone I took a look at the code. Everything looks good, but it is basically a simplified version of what I just added (which also prints feedback when there are no tasks running, and also prints the worlds in order). That being said, I'll close this now, but I appreciate the effort taken regardless. Thank you!

As for using the progress command, simply download Chunky 1.2.99 or higher for your server platform from [Actions](https://github.com/pop4959/Chunky/actions) or [CodeMC](https://ci.codemc.io/view/Author/job/pop4959/job/Chunky/) and you should be good to go.

**Comment by Jamalam360** [comment]
Haha lmao I didn't see that command 🤣

Thanks for looking at it anyways

**Comment by pop4959** [comment]
Well, it *was* just added recently. I had just refactored the progress stuff last week to make this a bit more doable. :D

No problem!

**Pull request closed without merging**
